FROM node:10.15-alpine

ARG DEBUG
ARG APP_PORT
ARG MONGO_HOST
ARG MONGO_USER
ARG MONGO_PASS
ARG MONGO_PORT
ARG MONGO_DB
ARG MONGO_SRV
ARG TOKEN_EXPIRES_IN
ARG JWT_PASSWORD


ENV DEBUG=${DEBUG}
ENV APP_PORT=${APP_PORT}
ENV MONGO_HOST=${MONGO_HOST}
ENV MONGO_USER=${MONGO_USER}
ENV MONGO_PASS=${MONGO_PASS}
ENV MONGO_PORT=${MONGO_PORT}
ENV MONGO_DB=${MONGO_DB}
ENV MONGO_SRV=${MONGO_SRV}
ENV TOKEN_EXPIRES_IN=${TOKEN_EXPIRES_IN}
ENV JWT_PASSWORD=${JWT_PASSWORD}

COPY . /home/node/app/

WORKDIR /home/node/app

RUN npm run build